-
  branches:
    only:
      - master
   
  version: 3.0.5
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
   
  os: Visual Studio 2015
  
  install:
    - ps: .\install.ps1
  
  before_build:
    - ps : .\build-before_build.ps1
  
  build:
    verbosity: minimal
    parallel: true
    publish_nuget: true
   
  configuration: Release
  cache:
    - src\packages -> **\packages.config
  
  services:
    - mongodb
  
  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'

  artifacts:
    - path: '*.nupkg'
  
  on_finish:
    - ps : .\build-on_finish.ps1   
  
  deploy:
    - provider: Environment
      name: NuGet.org
      on:
        branch: master
    
    - provider: GitHub
      description: ''
      auth_token:
        secure: +QYYXf1o06ZxmMAfGQN/n3rfgIHtjY9JcFRvps5vmbqkjWqa9PT7Z84poPCelWz8
      artifact: /.*\.nupkg/
      draft: false
      prerelease: false
      on:
        branch: master

-
  branches:
    only:
      - beta
   
  version: 3.0.0-beta5
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
   
  os: Visual Studio 2015
  
  install:
    - ps: .\install.ps1
  
  before_build:
    - ps : .\build-before_build.ps1
  
  build:
    verbosity: minimal
    parallel: true
    publish_nuget: true
   
  configuration: Release
  cache:
    - src\packages -> **\packages.config
  
  services:
    - mongodb
  
  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'

  artifacts:
    - path: '*.nupkg'
  
  on_finish:
    - ps : .\build-on_finish.ps1   
  
  deploy:
    - provider: Environment
      name: NuGet.org
      on:
        branch: beta

