  branches:
    only:
      - master
   
  version: 0.0.0-alpha{build}
  
  assembly_info:
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
    file: AssemblyInfo.*
    patch: true
   
  os: Visual Studio 2015
  
  before_build:
    - ps : .\build-before_build.ps1
  
  build:
    verbosity: minimal
    parallel: true
    publish_nuget: true
   
  configuration: Release
  cache:
    - src\packages -> **\packages.config
  
  test:
    assemblies:
      - '**\*.Tests.dll'
      - '**\*.FunctionalTests.dll'

  artifacts:
    - path: '*.nupkg'
  
  on_finish:
    - ps : .\build-on_finish.ps1   
  
  deploy:
    - provider: Environment
      name: NugGet.org
      on:
        branch: master
